- packages/metrics/modules/create-metric-types/create-metric-types.js
I've made this refactor to simplify the process of adding new metrics in the future. Based in this change, I'm going to issue a new MR adding the **http_requests_total** metric, which is missing from this library.
> Refactor create-metric-types.js

- packages/metrics/modules/create-request-observer/create-request-observer.js
Fixes #26 by allowing seconds as float, in order to respect [Prometheus Best Practices](https://prometheus.io/docs/practices/naming/#base-units) and have a good enough precision for calculations.
> feat(request-observer): change seconds duration precision to float

- packages/server/modules/server/server.js
The `listen` call passes an `error` to the callback we should reject the promise with if it's set.
> fix(server): add rejection when server creation fails

- packages/hapi/modules/index.js
- packages/hapi/modules/plugin/plugin.js
fix missing attributes error when register plugin with HapiJS: ` "[1] "attributes" is required"` BY:
- add/export instrument for plugin registration
e.g.
const server = new hapi.Server();
const promster = require('@promster/hapi');
promster.instrument(server, options);
related to issue: https://github.com/tdeekens/promster/issues/131
> fix missing attributes when register plugin

- packages/fastify/modules/index.js
- packages/fastify/modules/plugin/index.js
- packages/fastify/modules/plugin/plugin.js
- packages/fastify/modules/plugin/plugin.spec.js
- packages/fastify/package.json
- packages/fastify/readme.md
- readme.md
- yarn.lock
this PR adds support to https://github.com/fastify/fastify 
Related issue: https://github.com/tdeekens/promster/issues/168
Implementation is very similar to express middleware.
- There is a plugin which has initialization step to enable gc observer and decorate fastify object with `Prometheus` and `recordRequest` properties.
- Plugin attaches `onRequest` and `onResponse` event listeners to track `hrtime` and record request metrics in the end.
- It also registers an endpoint to serve metrics for Prometheus.
> feat(fatify): add plugin

- packages/express/modules/middleware/middleware.js
- packages/fastify/modules/plugin/plugin.js
- packages/hapi/modules/plugin/plugin.js
- readme.md
This augments `request` and `response` to be passed to all normalizers. This will be non-breaking as the standard argument (1st) will remain unchainged.
Closes #201
> feat: add passing request, response to normalizers

- readme.md
The README covers the Prometheus metrics and goes over how it provides a counter, histogram, and summary. While describing the histogram and summary the sections refer to each other, but both sections use the word "summary" which could confuse users unfamiliar with the details of Prometheus' Histograms and Summaries.
Covered in Summary.
No tech debt introduced with this PR.
> Correct summary/histogram references in README

- packages/metrics/modules/create-metric-types/create-metric-types.js
Prefixes http_requests_total metric with the provided prefix. [See issue](https://github.com/tdeekens/promster/issues/257)
> fix: prefix http_requests_total metrics

- readme.md
There was a ':' instead of a ';'
> Fixed Fastify Code Example

- packages/express/package.json
- packages/hapi/package.json
- packages/marblejs/package.json
- packages/metrics/package.json
- packages/server/package.json
This is needed as a dependency as it's a runtime we need.
Closes #356
> fix: add tslib as dependency

- .changeset/popular-melons-relate.md
- packages/hapi/modules/plugin/plugin.ts
This was an accidental breaking change when switching to TypeScript, probably because Hapi's typings are insufficient in this case.
When decorating with the `server` type, the decorator method doesn't have to be a function, and any value will work.
Fixes https://github.com/tdeekens/promster/issues/372
> @promster/hapi decorator fix

- .changeset/weak-coins-admire.md
- packages/types/index.ts
Make `buckets` and `percentiles` optional in `TPromsterOptions`
Self explanatory, Fixes #378
> fix(types): update TPromsterOptions

- .changeset/fast-waves-hope.md
- packages/hapi/modules/plugin/plugin.ts
- packages/hapi/package.json
Supports properly setting `status_code` when a Hapi response is actually a Boom object.
A common pattern for Hapi applications is to use [Boom objects](https://github.com/hapijs/boom) in responses. Under the hood, Hapi swaps the `response` object with the supplied Boom object. The result of this is that `status_code` is not populated properly when adding metrics - the `status_code` will simply be `undefined` in cases where a response was delegated from a Boom object.
This change introduces support for extracting the correct status code off a Boom object while maintaining the existing behavior for pulling status codes off normal `response` objects.
N/A
> fix(hapi): use correct status code attribute when Hapi responses are Boom errors

- packages/hapi/modules/index.ts
- packages/hapi/modules/plugin/plugin.ts
- packages/hapi/package.json
- yarn.lock
Thanks for this great library
This updates the hapi package to use the newer `@hapi/hapi` types which were [introduced in 18.2.0](https://github.com/hapijs/hapi/commit/eb89f71df7f8ecc48559eeeffbe3414205b45691)
This only adjusts some typescript imports to make it work when using newer hapi versions.
__Note__: `@hapi/boom` is added as dev dependency because `@types/hapi__boom` says to use `@hapi/boom` as it ships the correct type definitions:
https://www.npmjs.com/package/@types/hapi__boom
> @hapi/boom provides its own type definitions, so you don't need @types/hapi__boom installed!
This might be a breaking change as users with old hapi might have incompatible type definitions when trying to register this plugin over the old hapi types.
> feat: use @hapi/hapi in the hapi package

- .changeset/flat-pots-repeat.md
- .changeset/gorgeous-buses-fly.md
- .github/workflows/test.yml
- packages/hapi/modules/index.ts
- packages/hapi/modules/plugin/plugin.ts
- packages/hapi/package.json
- yarn.lock
In #472  we started using `@hapi/hapi` which requires node v12. This pull request updates the package (which is breaking) to that version.
> breaking(hapi): to bump required node to v12

- .changeset/four-pigs-relax.md
- packages/express/modules/middleware/middleware.ts
When we use a createMiddleware TS throw an error of wrong object (Express application).
`Type 'Application' is missing the following properties from type 'TApp': setTimeout, maxHeadersCount, timeout, headersTimeout, and 9 more.ts(2740)`
solves #499
> fix(express-type): changed TApp type

- .changeset/short-kids-walk.md
- packages/fastify/modules/plugin/plugin.ts
- packages/fastify/package.json
- yarn.lock
BREAKING CHANGE: now requires fastify >= 3
This updates the promster/fastify package to be compatible with [fastify@3 which was released in july](https://github.com/fastify/fastify/releases/tag/v3.0.0).
This is a breaking change for users that use `@promster/fastify` with fastify@2.
> feat: upgrade @promster/fastify to support fastify@3

- .cspell.json
- .github/workflows/test.yml
- packages/hapi/src/plugin/plugin.ts
- packages/metrics/src/create-metric-types/create-metric-types.ts
- packages/metrics/src/create-request-recorder/create-request-recorder.spec.js
- packages/metrics/src/create-request-recorder/create-request-recorder.ts
- readme.md
- red-chefs-smoke.md
This PR lets the GitHub workflow run spell check.
An added step in the `install` workflow on GitHub Actions run `cspell` commmand to check spelling in `*.md` and `*.ts` files.
The dictionary might be a bit tedious to maintain?
> Spell check

- .changeset/happy-coats-jam.md
- packages/metrics/package.json
> fix: typescript dev dependency of ts-essentials

- .changeset/proud-cobras-fetch.md
- packages/express/src/middleware/middleware.ts
- packages/fastify/src/plugin/plugin.ts
- packages/hapi/src/plugin/plugin.ts
- packages/marblejs/src/middleware/middleware.ts
- packages/metrics/src/create-gc-observer/create-gc-observer.ts
- packages/types/src/index.ts
- readme.md
Adds feature to pass `disableGcMetrics` when set to `true` no Garbage Collection metrics will be collected.
> feat: allow disabling Garbage Collection metrics

- .changeset/new-carrots-admire.md
- package.json
- packages/apollo/src/index.ts
- packages/apollo/src/plugin/plugin.ts
- packages/express/src/index.ts
- packages/express/src/middleware/middleware.ts
- packages/fastify/src/index.ts
- packages/fastify/src/plugin/plugin.ts
- packages/hapi/src/index.ts
- packages/hapi/src/plugin/plugin.ts
- packages/marblejs/src/index.ts
- packages/marblejs/src/middleware/middleware.ts
- packages/metrics/src/create-request-recorder/create-request-recorder.spec.js
- packages/metrics/src/create-request-recorder/create-request-recorder.ts
- packages/metrics/src/end-measurement-from/end-measurement-from.spec.js
- packages/metrics/src/end-measurement-from/end-measurement-from.ts
- packages/metrics/src/index.ts
- packages/metrics/src/timing/index.ts
- packages/metrics/src/timing/timing.spec.js
- packages/metrics/src/timing/timing.ts
- packages/types/src/index.ts
- readme.md
Closes #790
Using `process.hrtime.bigint` over only `process.hrtime()`.
> refactor: to use process.hrtime.bigint

- .changeset/popular-worms-cry.md
- packages/metrics/package.json
- yarn.lock
Resolves the following deprecation warning when using `promster/metrics`
```
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
````
The warning is due to `promster/metrics` using the (external) `url` package. NodeJS provides the same functionality which was deprecated for some time, [but that has been revoked](https://nodejs.org/api/url.html#legacy-url-api).
By just removing the dependency, the Node module is used (again) and tests run still successfully.
See also the issue #845.
> Use NodeJS url module instead of deprecated transitive dependency

- .changeset/seven-timers-occur.md
- packages/apollo/package.json
- packages/apollo/src/plugin/plugin.spec.js
- packages/apollo/src/plugin/plugin.ts
- yarn.lock
This is to demonstrate a potential bug with capturing error metrics in execute phase, and possible fix.
Errors are not recorded when thrown in execute phase.
> Attempt to illustrate execute phase bug

- .changeset/tame-berries-collect.md
- packages/apollo/src/plugin/plugin.spec.js
- packages/express/src/middleware/middleware.spec.js
- packages/fastify/src/plugin/plugin.spec.js
- packages/hapi/src/plugin/plugin.spec.js
- packages/marblejs/src/middleware/middleware.spec.js
- packages/metrics/src/create-gc-metrics/create-gc-metrics.ts
- packages/server/src/server/server.spec.js
- readme.md
Currently, promster exposes a metrics named `up` as an indication whether nodejs server is up or not.
The name `up` is conflicting with the similarily named metrics `up` automatically generated by prometheus.
I suggest in this PR to rename the promster metric `up` with something else: `nodejs_up`
Whenever a Prometheus scrapes a target, it will automatically generate and store a metrics named `up` (among others) : [link to docs](https://prometheus.io/docs/concepts/jobs_instances/#automatically-generated-labels-and-time-series)
In prometheus, this `up` means that prometheus could scrape the target (1) or failed to reach and scrape the target (0).
However in our case, the target (the app using promster to exposes metrics)  also exposes a metric named `up`. It has a different purpose, a …
> rename metrics `up`
